"""Add user_subscription and subscription table

Revision ID: 08bf4c1d5eca
Revises: 02823c806504
Create Date: 2025-08-10 13:41:06.063339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '08bf4c1d5eca'
down_revision: Union[str, Sequence[str], None] = '02823c806504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('tokens_allowed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=True)
    op.add_column('user_subscriptions', sa.Column('plan_id', sa.String(length=36), nullable=False))
    op.add_column('user_subscriptions', sa.Column('active', sa.Boolean(), nullable=False))
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_subscriptions', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_column('user_subscriptions', 'tokens_allowed')
    op.drop_column('user_subscriptions', 'duration_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('duration_days', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_subscriptions', sa.Column('tokens_allowed', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.alter_column('user_subscriptions', 'end_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_subscriptions', 'start_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('user_subscriptions', 'active')
    op.drop_column('user_subscriptions', 'plan_id')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
