"""fix tables

Revision ID: 18388a0ddb93
Revises: 06239c61bec2
Create Date: 2025-07-10 14:49:28.131506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18388a0ddb93'
down_revision: Union[str, Sequence[str], None] = '06239c61bec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_archives', 'ai_models', ['ai_model_id'], ['id'])
    op.create_foreign_key(None, 'ai_archives', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_archives', type_='foreignkey')
    op.drop_constraint(None, 'ai_archives', type_='foreignkey')
    # ### end Alembic commands ###
