"""Add enum value to type column in ai_models tables

Revision ID: 1954d254970e
Revises: 2f3c06c6031e
Create Date: 2025-07-03 08:22:17.797267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1954d254970e'
down_revision: Union[str, Sequence[str], None] = '2f3c06c6031e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
