"""Add user_subscription table

Revision ID: 48ebf27f93cc
Revises: 3792e0b4cb71
Create Date: 2025-08-10 13:30:51.684093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ebf27f93cc'
down_revision: Union[str, Sequence[str], None] = '3792e0b4cb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('domain', sa.String(length=255), nullable=False))
    op.add_column('assistants', sa.Column('slug', sa.String(length=36), nullable=False))
    op.create_unique_constraint(None, 'assistants', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assistants', type_='unique')
    op.drop_column('assistants', 'slug')
    op.drop_column('assistants', 'domain')
    # ### end Alembic commands ###
