"""Add file_uploads tables

Revision ID: 89840fbb4b56
Revises: ae4a798227bd
Create Date: 2025-07-02 10:49:34.523731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '89840fbb4b56'
down_revision: Union[str, Sequence[str], None] = 'ae4a798227bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
