"""Add Payment table

Revision ID: a11421b61974
Revises: 
Create Date: 2025-08-19 12:40:22.290253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a11421b61974'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_subscription_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('wallet_topup', 'subscription_direct', 'subscription_wallet', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('discount_code', sa.String(length=256), nullable=True),
    sa.Column('transaction_id', sa.String(length=256), nullable=True),
    sa.Column('invoice_number', sa.String(length=256), nullable=True),
    sa.Column('authority', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['user_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=True)
    op.add_column('subscription_plans', sa.Column('amount', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'amount')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
